AWSTemplateFormatVersion: 2010-09-09
Description: An AppSync API with JavaScript resolvers with a DynamoDB data source

Parameters:
  AppSyncSchemaS3Location:
    Description: S3 object where AppSync schema is stored
    Type: String
  CreateToDoResolverS3Location:
    Description: S3 object where Create ToDo resolver code is stored
    Type: String
  UpdateToDoResolverS3Location:
    Description: S3 object where Update ToDo resolver code is stored
    Type: String
  DeleteToDoResolverS3Location:
    Description: S3 object where Delete ToDo resolver code is stored
    Type: String
  GetToDoResolverS3Location:
    Description: S3 object where Get ToDo resolver code is stored
    Type: String
  ListToDoResolverS3Location:
    Description: S3 object where List ToDo resolver code is stored
    Type: String
  QueryToDosResolverS3Location:
    Description: S3 object where Query ToDo resolver code is stored
    Type: String
Resources:
  TodoAPI:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      AuthenticationType: API_KEY
      Name: SimpleTodoAPI
  TodoAPISchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt TodoAPI.ApiId
      DefinitionS3Location: !Ref AppSyncSchemaS3Location
  DefaultAPIKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt TodoAPI.ApiId
    DependsOn:
      - TodoAPISchema
  DataSourceServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
        Version: '2012-10-17'
  ServiceRoleDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:ConditionCheckItem
              - dynamodb:DeleteItem
              - dynamodb:DescribeTable
              - dynamodb:GetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:PutItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:UpdateItem
            Effect: Allow
            Resource:
              - !GetAtt TodoTable.Arn
              - Fn::Join:
                  - ''
                  - - !GetAtt TodoTable.Arn
                    - /index/*
        Version: '2012-10-17'
      PolicyName: ServiceRoleDefaultPolicy
      Roles:
        - !Ref DataSourceServiceRole
  TodoTableDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt TodoAPI.ApiId
      Name: table
      Type: AMAZON_DYNAMODB
      DynamoDBConfig:
        AwsRegion: !Ref AWS::Region
        TableName: !Ref TodoTable
      ServiceRoleArn: !GetAtt DataSourceServiceRole.Arn
  CreateTodoResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt TodoAPI.ApiId
      FieldName: createTodo
      TypeName: Mutation
      DataSourceName: table
      Runtime:
        Name: 'APPSYNC_JS'
        RuntimeVersion: '1.0.0'
      CodeS3Location: !Ref CreateToDoResolverS3Location
    DependsOn:
      - TodoAPISchema
      - TodoTableDataSource
  UpdateTodoResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt TodoAPI.ApiId
      FieldName: updateTodo
      TypeName: Mutation
      DataSourceName: table
      Runtime:
        Name: 'APPSYNC_JS'
        RuntimeVersion: '1.0.0'
      CodeS3Location: !Ref UpdateToDoResolverS3Location
    DependsOn:
      - TodoAPISchema
      - TodoTableDataSource
  DeleteTodoResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt TodoAPI.ApiId
      FieldName: deleteTodo
      TypeName: Mutation
      DataSourceName: table
      Runtime:
        Name: 'APPSYNC_JS'
        RuntimeVersion: '1.0.0'
      CodeS3Location: !Ref DeleteToDoResolverS3Location
    DependsOn:
      - TodoAPISchema
      - TodoTableDataSource
  GetTodoResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt TodoAPI.ApiId
      FieldName: getTodo
      TypeName: Query
      DataSourceName: table
      Runtime:
        Name: 'APPSYNC_JS'
        RuntimeVersion: '1.0.0'
      CodeS3Location: !Ref GetToDoResolverS3Location
    DependsOn:
      - TodoAPISchema
      - TodoTableDataSource
  ListTodosResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt TodoAPI.ApiId
      FieldName: listTodos
      TypeName: Query
      DataSourceName: table
      Runtime:
        Name: 'APPSYNC_JS'
        RuntimeVersion: '1.0.0'
      CodeS3Location: !Ref ListToDoResolverS3Location
    DependsOn:
      - TodoAPISchema
      - TodoTableDataSource
  QueryTodosResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt TodoAPI.ApiId
      FieldName: queryTodosByOwnerIndex
      TypeName: Query
      DataSourceName: table
      Runtime:
        Name: 'APPSYNC_JS'
        RuntimeVersion: '1.0.0'
      CodeS3Location: !Ref QueryToDosResolverS3Location
    DependsOn:
      - TodoAPISchema
      - TodoTableDataSource
  TodoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: owner
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: owner-index
          KeySchema:
            - AttributeName: owner
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
